### ISSUE TITLE
Support for other keyboard layout

### ISSUE THREAD

**Issue by magicpritt** [salty-horse/ibus-uniemoji#29]
Is there a way to add support for other keyboard layouts, such as [QWERTZ](https://en.wikipedia.org/wiki/QWERTZ) or [AZERTY](https://en.wikipedia.org/wiki/AZERTY) ?
Searching for emoji is a little awkward when you're used to another layout than QWERTY.

**Comment by salty-horse** [comment]
By default, IBus uses the layout of the previous input method.
This caused me problems, since I have to cycle from English to Hebrew to Uniemoji, and then all I could enter was Hebrew characters.

In commit 75bdd39848a385b6aa00fb09fc5eb56bdcb7df7f I forced it to always use the "us" layout. You're welcome to change it to something else before installing.

Maybe I should make it configurable when running `make`.

**Comment by magicpritt** [comment]
Indeed, that's working.
Thanks
